let mname = document.querySelector(".movie");
let gen = document.querySelector("button");
gen.addEventListener("click", ()=>{
    let act = [
        "1983",
        "22 Female Kottayam",
        "Aa Raathri",
        "Aaram Thamburan",
        "Aavanazhi",
        "Aayiram Naavulla Ananthan",
        "Achuvinte Amma",
        "Adaminte Makan Abu",
        "Adiyozhukkukal",
        "Advaitham",
        "Ahimsa",
        "Akashadoothu",
        "Akkare Akkare Akkare",
        "Alexander the Great",
        "Amaram",
        "Amen",
        "Android Kunjappan Ver 5.25",
        "Angamaly Diaries",
        "Aniyathipraavu",
        "Anjaam Pathiraa",
        "Annan Thambi",
        "Aparan",
        "Arayannangalude Veedu",
        "Athirathram",
        "August 1",
        "Ayal Kadha Ezhuthukayanu",
        "Ayalathe Adheham",
        "Ayyappanum Koshiyum",
        "Azhakiya Ravanan",
        "Balettan",
        "Balram vs. Tharadas",
        "Bangalore Days",
        "Best Actor",
        "Bharatham",
        "Bharathchandran IPS",
        "Bheeshma Parvam",
        "Bhoothakkannadi",
        "Bhramaram",
        "Big B",
        "Black",
        "C U Soon",
        "C.I.D. Moosa",
        "Calcutta News",
        "Casanovva",
        "Celluloid",
        "Chandranudikkunna Dikhil",
        "Charlie",
        "Chess",
        "Chinthamani Kolacase",
        "Chithram",
        "Chotta Mumbai",
        "Christian Brothers",
        "Chronic Bachelor",
        "CID Moosa",
        "CID Unnikrishnan B.A., B.Ed.",
        "Classmates",
        "College Kumaran",
        "Commissioner",
        "Commissioner 2",
        "Crazy Gopalan",
        "Crime File",
        "Dada Sahib",
        "Dasharatham",
        "Desadanam",
        "Devadoothan",
        "Devasuram",
        "Dhruvam",
        "Dr. Babasaheb Ambedkar",
        "Drishyam",
        "Drishyam 2",
        "Dubai",
        "Ee Pattanathil Bhootham",
        "Ee. Ma. Yau",
        "Ekalavyan",
        "Ennu Ninte Moideen",
        "FIR",
        "Flash",
        "Forensic",
        "Friends",
        "Geethanjali",
        "Godfather",
        "Grandmaster",
        "Halal Love Story",
        "Helen",
        "Highway",
        "His Highness Abdullah",
        "Hitler",
        "Home",
        "How Old Are You",
        "Hridayam",
        "In Harihar Nagar",
        "Indian Rupee",
        "Innale",
        "Inspector Balram",
        "Inspector Garud",
        "Iruvar",
        "Ishq",
        "Ishtam",
        "Ittymaani: Made in China",
        "Ivan Maryadaraman",
        "Jack & Daniel",
        "Jagratha",
        "Jallikattu",
        "Jana Gana Mana",
        "Janakan",
        "Joji",
        "Joker",
        "Joseph",
        "July 4",
        "Kaalapani",
        "Kaaryasthan",
        "Kaazhcha",
        "Kadha Thudarunnu",
        "Kaliyattam",
        "Kaliyoonjal",
        "Kalyanaraman",
        "Kammara Sambhavam",
        "Kammatti Paadam",
        "Kannezhuthi Pottum Thottu",
        "Kappela",
        "Kariyilakkattu Pole",
        "Karmayodha",
        "Kashmeeram",
        "Katha Parayumpol",
        "Kauravar",
        "Kayamkulam Kochunni",
        "Kazhcha",
        "Keerthi Chakra",
        "Kerala Cafe",
        "Kerala Varma Pazhassi Raja",
        "Keshu Ee Veedinte Nadhan",
        "Kettiyollaanu Ente Maalakha",
        "Kilichundan Mampazham",
        "Kilometers and Kilometers",
        "Kilukkam",
        "King Liar",
        "Kireedam",
        "Kochu Kochu Santhoshangal",
        "Kodathi Samaksham Balan Vakeel",
        "Koodevide",
        "Kumbalangi Nights",
        "Kunjikoonan",
        "Kuruthi",
        "Kusruthi Kuruppu",
        "Kutty Srank",
        "Ladies and Gentleman",
        "Lailaa O Lailaa",
        "Lelam",
        "Life of Josutty",
        "Lion",
        "Lokpal",
        "Loudspeaker",
        "Lucifer",
        "Madampi",
        "Mafia",
        "Maheshinte Prathikaaram",
        "Malik",
        "Mamangam",
        "Mambazhakkalam",
        "Mammootty the Best Actor",
        "Manassinakkare",
        "Manathe Kottaram",
        "Manichitrathazhu",
        "Marakkar: Arabikadalinte Simham",
        "Marykkundoru Kunjaadu",
        "Mathilukal",
        "Mayamohini",
        "Mayavi",
        "Meesa Madhavan",
        "Megham",
        "Meleparambil Aanveedu",
        "Midhunam",
        "Minnal Murali",
        "Mohanlal",
        "Moonnam Pakkam",
        "Mr. Fraud",
        "Mr. Marumakan",
        "Mrigaya",
        "Mulla",
        "Munnariyippu",
        "Munthirivallikal Thalirkkumbol",
        "My Boss",
        "My Santa",
        "Nadodikattu",
        "Nair Saab",
        "Namukku Parkkan Munthirithoppukal",
        "Nandanam",
        "Naran",
        "Narasimham",
        "Nasrani",
        "Natturajavu",
        "Nayattu",
        "Neerali",
        "Nerariyan CBI",
        "New Delhi",
        "Nirakkoottu",
        "Njangal Santhushtaranu",
        "No. 20 Madras Mail",
        "North 24 Kaatham",
        "Odiyan",
        "Om Shanti Oshana",
        "One",
        "Oppam",
        "Orma Mathram",
        "Oru CBI Diary Kurippu",
        "Oru Maravathoor Kanavu",
        "Oru Vadakkan Veeragadha",
        "Oru Vadakkan Veeragatha",
        "Pada",
        "Padayottam",
        "Paithrukam",
        "Paleri Manikyam",
        "Paleri Manikyam: Oru Pathirakolapathakathinte Katha",
        "Pandippada",
        "Pappayude Swantham Appoos",
        "Pappy Appacha",
        "Paradesi",
        "Parakkum Pappan",
        "Parunthu",
        "Passenger",
        "Pathemari",
        "Pathram",
        "Pattabhishekam",
        "Pavithram",
        "Peranbu",
        "Peruchazhi",
        "Perumthachan",
        "Peruvannapurathe Visheshangal",
        "Ponthan Mada",
        "Pookkalam Varavayi",
        "Pranayam",
        "Pranchiyettan and the Saint",
        "Premam",
        "Pulimurugan",
        "Punjabi House",
        "Rajamanikyam",
        "Rajavinte Makan",
        "Rakshasa Rajavu",
        "Ramaleela",
        "Ramji Rao Speaking",
        "Rappakal",
        "Rasathanthram",
        "Ravanaprabhu",
        "Ring Master",
        "Rock n' Roll",
        "Rorschach",
        "Rudraksham",
        "Run Baby Run",
        "Runway",
        "Sadayam",
        "Sagar Alias Jacky Reloaded",
        "Salt n' Pepper",
        "Sandesham",
        "Sandhyakku Virinja Poovu",
        "Sangham",
        "Sathyamev Jayate",
        "Sethurama Iyer CBI",
        "Shikkar",
        "Shylock",
        "Soorya Manasam",
        "Sooryamanasam",
        "Sound Thoma",
        "Spadikam",
        "Spirit",
        "Sringaravelan",
        "Stalin Sivadas",
        "Sudani from Nigeria",
        "Summer in Bethlehem",
        "Swapnakoodu",
        "Swayamvarapanthal",
        "Take Off",
        "Thalapathi",
        "Thalastaanam",
        "Thalasthanam",
        "Thalavattam",
        "Thallumaala",
        "Thandavam",
        "Thaniyavarthanam",
        "Thanmathra",
        "Thazhvaram",
        "The Don",
        "The Great Indian Kitchen",
        "The King",
        "The King and the Commissioner",
        "The Priest",
        "The Tiger",
        "The Truth",
        "Thenali",
        "Thenkasipattanam",
        "Thilakkam",
        "Thirakkatha",
        "Thommanum Makkalum",
        "Thondimuthalum Driksakshiyum",
        "Thooval Kottaram",
        "Thoovanathumbikal",
        "Thuruppu Gulan",
        "Traffic",
        "Trance",
        "Twenty:20",
        "Two Countries",
        "Udayananu Tharam",
        "Unda",
        "Ustad Hotel",
        "Utharam",
        "Uyare",
        "Vadakkumnathan",
        "Vadakkunokkiyantram",
        "Valliettan",
        "Valyettan",
        "Vanaprastham",
        "Varane Avashyamund",
        "Vazhunnor",
        "Veendum CBI",
        "Veendum Chila Veettukaryangal",
        "Velipadinte Pusthakam",
        "Vellanakalude Nadu",
        "Veruthe Oru Bharya",
        "Vesham",
        "Vidheyan",
        "Vietnam Colony",
        "Villain",
        "Villali Veeran",
        "Virus",
        "Welcome to Central Jail",
        "Yathra",
        "Yathrakarude Sradhakku",
        "Yavanika",
        "Yodha"
      ];
    let l = act.length;
    console.log(act.length);
    let i = Math.floor(Math.random()*l);
    mname.innerText = act[i];
    if (i !== -1){
        act.splice(i,1);
    }
});

